#!/usr/bin/env bash
# 05-hysteria2.sh — установка Hysteria2 (UDP/443) с self-signed cert
# Ставит официальный бинарник от apernet/hysteria, отдельный systemd-сервис.

set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
config_load

HY_USER="hysteria"
HY_DIR="/etc/hysteria"
HY_BIN="/usr/local/bin/hysteria"

# ------------------------------------------------------------
# 1. Установка hysteria через официальный installer
# ------------------------------------------------------------

if [ -x "$HY_BIN" ]; then
    log_info "hysteria уже установлен ($($HY_BIN version 2>&1 | head -1))"
else
    log_info "устанавливаю hysteria через get.hy2.sh"
    # Официальный installer создаёт бинарник, юзера hysteria, systemd-сервис
    bash <(curl -fsSL https://get.hy2.sh/) >/dev/null 2>&1 \
        || die "hysteria installer failed"
    log_ok "hysteria установлен"
fi

# ------------------------------------------------------------
# 2. Self-signed cert на $HY2_SNI
# ------------------------------------------------------------

mkdir -p "$HY_DIR"
if [ ! -f "$HY_DIR/cert.pem" ] || [ ! -f "$HY_DIR/key.pem" ]; then
    log_info "генерирую self-signed cert на CN=$HY2_SNI"
    openssl ecparam -name prime256v1 -genkey -noout -out "$HY_DIR/key.pem"
    openssl req -new -x509 -days 36500 \
        -key "$HY_DIR/key.pem" \
        -out "$HY_DIR/cert.pem" \
        -subj "/CN=$HY2_SNI" \
        -addext "subjectAltName=DNS:$HY2_SNI" 2>/dev/null
    chmod 644 "$HY_DIR/cert.pem"
    chmod 600 "$HY_DIR/key.pem"
fi
# Hysteria запускается под юзером hysteria → даём ему чтение
if id "$HY_USER" >/dev/null 2>&1; then
    chown "$HY_USER:$HY_USER" "$HY_DIR/cert.pem" "$HY_DIR/key.pem"
fi

# ------------------------------------------------------------
# 3. Конфиг
# ------------------------------------------------------------

log_info "пишу /etc/hysteria/config.yaml"
cat > "$HY_DIR/config.yaml" <<EOF
# /etc/hysteria/config.yaml — generated by vpn-setup install.sh
listen: :${HY2_PORT}

tls:
  cert: ${HY_DIR}/cert.pem
  key: ${HY_DIR}/key.pem

auth:
  type: password
  password: ${HY2_PASSWORD}

# Маскировка под легитимный сайт: при HTTP-обращении на :443 отдаём bing
masquerade:
  type: proxy
  proxy:
    url: https://www.${HY2_SNI}/
    rewriteHost: true

# BBR конгестия + игнорим лимиты клиента (сервер сам подбирает темп)
ignoreClientBandwidth: true
EOF
chmod 644 "$HY_DIR/config.yaml"

# ------------------------------------------------------------
# 4. systemd
# ------------------------------------------------------------

if is_container; then
    log_warn "контейнер — systemd сервис hysteria-server не активирован"
else
    systemctl daemon-reload
    systemctl enable hysteria-server.service >/dev/null 2>&1 || true
    systemctl restart hysteria-server.service

    sleep 2
    if systemctl is-active --quiet hysteria-server.service; then
        log_ok "hysteria-server активен на UDP/${HY2_PORT}"
        ss -ulnp 2>/dev/null | grep -E ":${HY2_PORT}\b" | head -3 || true
    else
        log_err "hysteria-server не стартует. Логи:"
        journalctl -u hysteria-server.service -n 20 --no-pager
        die "hysteria-server failed"
    fi
fi

log_ok "Hysteria2 установлен"
