#!/usr/bin/env bash
# 06-amneziawg.sh — установка AmneziaWG v2 (UDP/$AWG_PORT) с CPS-обфускацией
# Требует ядро >= 6.2 (HWE на Ubuntu 22.04). См. 02-kernel-hwe.sh.

set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
config_load

AWG_DIR="/etc/amnezia/amneziawg"
SERVER_IP_TUN="${AWG_NETWORK%/*}"   # 10.66.66.0/24 → 10.66.66.0
NETWORK_BASE="${SERVER_IP_TUN%.*}"  # 10.66.66.0 → 10.66.66
SERVER_TUN_IP="${NETWORK_BASE}.1/24"
CLIENT_TUN_IP="${NETWORK_BASE}.2/32"

if is_container; then
    log_warn "контейнер — AmneziaWG требует kernel module, который нельзя собрать в Docker"
    log_warn "пропускаю установку. Скрипт ставит: PPA, packages, keys, config — без modprobe/awg-quick"
    SKIP_KERNEL_OPS=1
else
    SKIP_KERNEL_OPS=0
    # Проверяем ядро
    kernel_major="$(uname -r | cut -d. -f1)"
    kernel_minor="$(uname -r | cut -d. -f2)"
    if [ "$kernel_major" -lt 6 ] || { [ "$kernel_major" -eq 6 ] && [ "$kernel_minor" -lt 2 ]; }; then
        die "ядро $(uname -r) < 6.2 — AmneziaWG DKMS не соберётся. Запусти 02-kernel-hwe и сделай reboot."
    fi
fi

# ------------------------------------------------------------
# 1. PPA + пакеты
# ------------------------------------------------------------

log_info "добавляю PPA amnezia/ppa"
wait_for_apt
apt_install software-properties-common gnupg2

if ! grep -rq "amnezia/ppa" /etc/apt/sources.list /etc/apt/sources.list.d/ 2>/dev/null; then
    add-apt-repository -y ppa:amnezia/ppa >/dev/null 2>&1 || \
        log_warn "add-apt-repository вернул ошибку (это OK если PPA уже добавлен)"
fi

log_info "обновляю apt + устанавливаю amneziawg пакеты"
apt_update

if [ "$SKIP_KERNEL_OPS" = "0" ]; then
    apt_install \
        "linux-headers-$(uname -r)" \
        iptables resolvconf \
        amneziawg amneziawg-dkms amneziawg-tools
else
    # В контейнере — только tools без DKMS-сборки
    apt_install amneziawg-tools 2>&1 | tail -3 \
        || log_warn "amneziawg-tools тоже не ставится в контейнере — это ок"
fi

# ------------------------------------------------------------
# 2. modprobe + IP forwarding
# ------------------------------------------------------------

if [ "$SKIP_KERNEL_OPS" = "0" ]; then
    log_info "загружаю модуль amneziawg"
    modprobe amneziawg || die "modprobe amneziawg failed"
    lsmod | grep -q '^amneziawg' || die "amneziawg не в lsmod"
    log_ok "модуль amneziawg загружен"

    # IP forwarding (на случай если 00-bootstrap не применил)
    sysctl -w net.ipv4.ip_forward=1 >/dev/null
    sysctl -w net.ipv6.conf.all.forwarding=1 >/dev/null
fi

# ------------------------------------------------------------
# 3. Генерация ключей (если ещё нет)
# ------------------------------------------------------------

mkdir -p "$AWG_DIR"
chmod 700 "$AWG_DIR"
cd "$AWG_DIR"
umask 077

# Используем awg, если установлен; иначе wg (совместим)
KEYGEN="awg"
command -v awg >/dev/null 2>&1 || KEYGEN="wg"
command -v "$KEYGEN" >/dev/null 2>&1 || die "ни awg, ни wg не найдены"

if [ -z "${AWG_SERVER_KEY:-}" ] || [ -z "${AWG_SERVER_PUB:-}" ]; then
    log_info "генерирую серверный keypair"
    AWG_SERVER_KEY="$($KEYGEN genkey)"
    AWG_SERVER_PUB="$(printf '%s' "$AWG_SERVER_KEY" | $KEYGEN pubkey)"
    echo "$AWG_SERVER_KEY" > server.key && chmod 600 server.key
    echo "$AWG_SERVER_PUB" > server.pub
fi

if [ -z "${AWG_CLIENT_KEY:-}" ] || [ -z "${AWG_CLIENT_PUB:-}" ]; then
    log_info "генерирую клиентский keypair"
    AWG_CLIENT_KEY="$($KEYGEN genkey)"
    AWG_CLIENT_PUB="$(printf '%s' "$AWG_CLIENT_KEY" | $KEYGEN pubkey)"
    echo "$AWG_CLIENT_KEY" > client1.key && chmod 600 client1.key
    echo "$AWG_CLIENT_PUB" > client1.pub
fi

if [ -z "${AWG_CLIENT_PSK:-}" ]; then
    log_info "генерирую PSK"
    AWG_CLIENT_PSK="$($KEYGEN genpsk)"
    echo "$AWG_CLIENT_PSK" > client1.psk && chmod 600 client1.psk
fi

# Сохраняем в config.env
config_save

# ------------------------------------------------------------
# 4. Серверный конфиг awg0.conf
# ------------------------------------------------------------

IFACE="$(detect_default_iface)"
[ -n "$IFACE" ] || IFACE="eth0"

log_info "пишу $AWG_DIR/awg0.conf (uplink iface=$IFACE)"

cat > "$AWG_DIR/awg0.conf" <<EOF
# AmneziaWG v2 server config — generated by vpn-setup install.sh
[Interface]
PrivateKey = ${AWG_SERVER_KEY}
Address = ${SERVER_TUN_IP}
ListenPort = ${AWG_PORT}
MTU = 1420

# v1 obfuscation (junk packets + magic headers)
Jc = 8
Jmin = 50
Jmax = 1000
S1 = 96
S2 = 96
S3 = 32
S4 = 0
H1 = 1700000001
H2 = 1700000100-1700000199
H3 = 1700000300
H4 = 1700000500-1700000999

# v2 CPS — обязательно! Без этих полей работает как v1.
# I1 = первый пакет выглядит как TLS 1.0 ClientHello: 16 03 01 01 + 32 random bytes
# I2 = ответ: timestamp (4 bytes) + 16 random char-bytes
I1 = <b 0x16030101><r 32>
I2 = <t><rc 16>

PostUp   = iptables -I FORWARD -i %i -j ACCEPT; iptables -I FORWARD -o %i -j ACCEPT; iptables -t nat -A POSTROUTING -s ${AWG_NETWORK} -o ${IFACE} -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT; iptables -t nat -D POSTROUTING -s ${AWG_NETWORK} -o ${IFACE} -j MASQUERADE

[Peer]
PublicKey = ${AWG_CLIENT_PUB}
PresharedKey = ${AWG_CLIENT_PSK}
AllowedIPs = ${CLIENT_TUN_IP}
EOF
chmod 600 "$AWG_DIR/awg0.conf"

# ------------------------------------------------------------
# 5. systemd: awg-quick@awg0
# ------------------------------------------------------------

if [ "$SKIP_KERNEL_OPS" = "0" ]; then
    log_info "включаю awg-quick@awg0"
    systemctl enable --now awg-quick@awg0 >/dev/null 2>&1 || die "awg-quick@awg0 не стартует"

    sleep 1
    if awg show awg0 2>/dev/null | head -3; then
        log_ok "awg0 поднят"
        # Если v2 (CPS) активен — должны быть видны i1/i2
        if awg show awg0 2>/dev/null | grep -qE '\bi[12]\b'; then
            log_ok "v2 CPS активен (видны i1/i2)"
        else
            log_warn "v2 CPS не виден в awg show — возможно работает как v1"
        fi
        ss -ulnp 2>/dev/null | grep ":${AWG_PORT}\b" | head -3 || true
    else
        log_err "awg show не работает"
        journalctl -u "awg-quick@awg0" -n 20 --no-pager
        die "awg0 failed"
    fi
else
    log_warn "контейнер — awg-quick@awg0 пропущен. На реальном VPS будет запущено автоматически."
fi

log_ok "AmneziaWG v2 установлен"
