#!/usr/bin/env bash
# 99-print-creds.sh — печать всех клиентских ссылок + сохранение в CREDENTIALS.md
#
# Генерирует:
#   - VLESS+Reality+Vision URL + QR в stdout
#   - Hysteria2 URL + QR в stdout
#   - AmneziaWG client.conf (рядом с config.env)
#   - CREDENTIALS.md в /root/

set -euo pipefail
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"
config_load

NETWORK_BASE="$(echo "${AWG_NETWORK%/*}" | awk -F. '{print $1"."$2"."$3}')"
CLIENT_TUN_IP="${NETWORK_BASE}.2/32"

# ------------------------------------------------------------
# 1. Сборка ссылок
# ------------------------------------------------------------

VLESS_LINK="vless://${VLESS_UUID}@${SERVER_IP}:${VLESS_PORT}?type=tcp&security=reality&pbk=${VLESS_PUB}&fp=chrome&sni=${VLESS_SNI}&sid=${VLESS_SID}&spx=%2F&flow=xtls-rprx-vision#${LABEL}-vless-${VLESS_PORT}"

HY2_LINK="hysteria2://${HY2_PASSWORD}@${SERVER_IP}:${HY2_PORT}/?insecure=1&sni=${HY2_SNI}#${LABEL}-hy2"

# ------------------------------------------------------------
# 2. AmneziaWG client.conf
# ------------------------------------------------------------

CLIENT_CONF="$(dirname "$CONFIG_FILE")/amneziawg-client.conf"
cat > "$CLIENT_CONF" <<EOF
# AmneziaWG v2 client config — generated by vpn-setup
# Импортировать в AmneziaVPN client (Settings → "У меня уже есть подключение")
[Interface]
PrivateKey = ${AWG_CLIENT_KEY}
Address = ${CLIENT_TUN_IP}
DNS = 1.1.1.1, 9.9.9.9
MTU = 1420

# Должны побайтно совпадать с сервером (Jc/Jmin/Jmax могут отличаться)
Jc = 8
Jmin = 50
Jmax = 1000
S1 = 96
S2 = 96
S3 = 32
S4 = 0
H1 = 1700000001
H2 = 1700000100-1700000199
H3 = 1700000300
H4 = 1700000500-1700000999
I1 = <b 0x16030101><r 32>
I2 = <t><rc 16>

[Peer]
PublicKey = ${AWG_SERVER_PUB}
PresharedKey = ${AWG_CLIENT_PSK}
Endpoint = ${SERVER_IP}:${AWG_PORT}
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 25
EOF
chmod 600 "$CLIENT_CONF"

# ------------------------------------------------------------
# 3. Печать в stdout
# ------------------------------------------------------------

cat <<HEADER

${C_GREEN}================================================================${C_RESET}
${C_GREEN} VPN SETUP — установка завершена ${C_RESET}
${C_GREEN}================================================================${C_RESET}

  Сервер:   ${SERVER_IP}
  Метка:    ${LABEL}

${C_BLUE}-- ПАНЕЛЬ 3X-UI --${C_RESET}
  URL:      http://${SERVER_IP}:${PANEL_PORT}/${PANEL_PATH}/
  User:     ${PANEL_USER}
  Pass:     ${PANEL_PASS}

${C_BLUE}-- VLESS+Reality+Vision (TCP/${VLESS_PORT}) --${C_RESET}
  SNI:      ${VLESS_SNI}
  UUID:     ${VLESS_UUID}
  Link:
${C_CYAN}${VLESS_LINK}${C_RESET}

HEADER

if command -v qrencode >/dev/null 2>&1; then
    echo "$VLESS_LINK" | qrencode -t ANSIUTF8 -m 1 || true
fi

cat <<HEADER

${C_BLUE}-- Hysteria2 (UDP/${HY2_PORT}) --${C_RESET}
  Пароль:   ${HY2_PASSWORD}
  SNI:      ${HY2_SNI}
  Link:
${C_CYAN}${HY2_LINK}${C_RESET}

HEADER

if command -v qrencode >/dev/null 2>&1; then
    echo "$HY2_LINK" | qrencode -t ANSIUTF8 -m 1 || true
fi

cat <<HEADER

${C_BLUE}-- AmneziaWG v2 (UDP/${AWG_PORT}) --${C_RESET}
  Сервер pubkey:  ${AWG_SERVER_PUB}
  Клиентский конфиг: ${CLIENT_CONF}

  Импортировать в AmneziaVPN: Settings → "У меня уже есть подключение"
  → выбрать ${CLIENT_CONF}

${C_GREEN}================================================================${C_RESET}

HEADER

# ------------------------------------------------------------
# 4. Сохраняем CREDENTIALS.md
# ------------------------------------------------------------

CRED_OUT="${VPN_CREDENTIALS_OUT:-/root/CREDENTIALS.md}"

cat > "$CRED_OUT" <<EOF
# CREDENTIALS — $(date -Iseconds)

> ⚠️ Секреты для сервера ${SERVER_IP}. Не коммитить, не шарить.

## SSH

- Host: \`${SERVER_IP}\`
- User: root (или твой логин)
- Аутентификация: см. ssh ключ который ты использовал для запуска install.sh

## Открытые порты (UFW)

| Порт | Протокол | Сервис |
|---|---|---|
| 22 | TCP | sshd |
| ${VLESS_PORT} | TCP | VLESS+Reality+Vision (xray, через 3x-ui) |
| ${PANEL_PORT} | TCP | 3x-ui панель |
| ${HY2_PORT} | UDP | Hysteria2 |
| ${AWG_PORT} | UDP | AmneziaWG v2 |

## Панель 3x-ui

- URL: http://${SERVER_IP}:${PANEL_PORT}/${PANEL_PATH}/
- Login: \`${PANEL_USER}\`
- Password: \`${PANEL_PASS}\`
- Путь к БД: \`/etc/x-ui/x-ui.db\`

## VLESS+Reality+Vision (TCP/${VLESS_PORT})

- Port: \`${VLESS_PORT}/tcp\`
- Flow: \`xtls-rprx-vision\`
- SNI / Reality dest: \`${VLESS_SNI}\`
- UUID: \`${VLESS_UUID}\`
- PrivateKey: \`${VLESS_PRIV}\`
- PublicKey: \`${VLESS_PUB}\`
- ShortId: \`${VLESS_SID}\`

### Клиентская ссылка
\`\`\`
${VLESS_LINK}
\`\`\`

## Hysteria2 (UDP/${HY2_PORT})

- Port: \`${HY2_PORT}/udp\`
- Password: \`${HY2_PASSWORD}\`
- SNI (self-signed cert CN): \`${HY2_SNI}\`
- Конфиг: \`/etc/hysteria/config.yaml\`
- Лог: \`journalctl -u hysteria-server.service\`

### Клиентская ссылка
\`\`\`
${HY2_LINK}
\`\`\`

## AmneziaWG v2 (UDP/${AWG_PORT})

- Port: \`${AWG_PORT}/udp\`
- Сеть: \`${AWG_NETWORK}\`
- MTU: 1420
- Сервер pubkey: \`${AWG_SERVER_PUB}\`
- Клиентский pubkey: \`${AWG_CLIENT_PUB}\`
- PSK: \`${AWG_CLIENT_PSK}\`
- Конфиг сервера: \`/etc/amnezia/amneziawg/awg0.conf\`
- Systemd: \`awg-quick@awg0\`

### Клиентский конфиг
Файл: \`${CLIENT_CONF}\` — импортировать в AmneziaVPN.
EOF
chmod 600 "$CRED_OUT"

log_ok "CREDENTIALS.md записан: $CRED_OUT"
log_ok "Конфиг скрипта (без секретов): $CONFIG_FILE"
